[TECH](SRE)
padoa/sorry-cypress pull request #27
Opened 2020-10-29 13:41 UTC by Hackatosh

2020-10-30 08:45 UTC, PaulLesur requested changes

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +        image: agoldis/sorry-cypress-api:latest
```suggestion
        image: padoa/sorry-cypress-api:master
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +          value: [YOUR-DASHBOARD-URL-HERE]
```suggestion
          value: sorry-cypress-dashboard.aodap-staging.fr
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +          value: sendible-cypress
```suggestion
          value: sorry-cypress
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +          value: us-east-1
eu-west-01

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +        image: agoldis/sorry-cypress-director:latest
padoa/sorry-cypress-director:master

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +          value: [YOUR-API-URL-HERE]
```suggestion
          value: sorry-cypress-api.aodap-staging.fr
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +        image: agoldis/sorry-cypress-dashboard:latest
```suggestion
        image: padoa/sorry-cypress-dashboard:master
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +  - host: [YOUR-DASHBOARD-URL-HERE]
```suggestion
  - host: sorry-cypress-dashboard.aodap-staging.fr
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +  - host: [YOUR-API-URL-HERE]
```suggestion
  - host: sorry-cypress-api.aodap-staging.fr
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +  - host: [YOUR-DIRECTOR-URL-HERE]
```suggestion
  - host: sorry-cypress-director.aodap-staging.fr
```

2020-10-30 08:45 UTC, PaulLesur commented on kubernetes-full.yml
> +  AWS_ACCESS_KEY_ID: [INSERT-HERE]
Sûrement un truc à mettre ici :sweat_smile:

2020-10-30 08:45 UTC, PaulLesur commented on k8s/sorry-cypress/values.yaml
> +    repository: registry.padoa.fr/padoa/sorry-cypress-director
Est ce qu'on ne prendrait pas depuis ACR pour rester coté Azure ?

2020-10-30 08:45 UTC, PaulLesur commented on k8s/sorry-cypress/values.yaml
> +    repository: registry.padoa.fr/padoa/sorry-cypress-dashboard
Est ce qu'on ne prendrait pas depuis ACR pour rester coté Azure ?

2020-10-30 08:45 UTC, PaulLesur commented on k8s/sorry-cypress/values.yaml
> +    repository: registry.padoa.fr/padoa/sorry-cypress-api
Est ce qu'on ne prendrait pas depuis ACR pour rester coté Azure ?

2020-10-30 08:45 UTC, PaulLesur commented on .circleci/config.yml
> +              docker push ${DOCKER_REGISTRY_HOSTNAME}/padoa/sorry-cypress-api:$FULL_TAG
Pousser vers ACR aussi je pense

2020-10-30 08:45 UTC, PaulLesur commented on .circleci/config.yml
> +              docker push ${DOCKER_REGISTRY_HOSTNAME}/padoa/sorry-cypress-director:$FULL_TAG
Pousser vers ACR aussi je pense

2020-10-30 08:45 UTC, PaulLesur commented on .circleci/config.yml
> +              docker push ${DOCKER_REGISTRY_HOSTNAME}/padoa/sorry-cypress-dashboard:$FULL_TAG
Pousser vers ACR aussi je pense

2020-10-30 10:50 UTC, PaulLesur requested changes

2020-10-30 10:50 UTC, PaulLesur commented on k8s/sorry-cypress/values.yaml
> +global: {}
```suggestion
global: 
    sorry_cypress_tag: master
```

2020-11-02 16:37 UTC, jambon69 commented on k8s/sorry-cypress/values.yaml
> +    annotations:
Rajoute peut-être l'annotation du forward-auth et du ip-whitelist, histoire que le dashboard soit pas ouvert pour tout le monde :) (je sais pas si l'ip whitelist est déja en place, mais le forward-auth c'est sur)

2020-11-02 16:37 UTC, jambon69 commented on k8s/sorry-cypress/templates/sorry-cypress-secrets.yaml
> +{{- if and .Values.aws_access_key_id .Values.aws_secret_access_key  }}
Un peu dommage d'avoir fait ça comme ça plutot que d'utiliser un fichier de template generic pour les secrets
(https://github.com/padoa/haw-infra/blob/master/k8s/efk/templates/secrets.yaml)

(Après c'est pas obligatoire, mais si on a besoin de nouveaux secrets ça peut être cool)

2020-11-03 08:29 UTC, merged